name: "🚀 Feature request"
description: Suggest a feature that will improve NuxtAuth
labels: ["pending", "enchantment"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition to NuxtAuth, including the possible use cases and alternatives you have considered. If you have a working prototype or module that implements it, please include a link.
      placeholder: Feature description
    validations:
      required: true
  - type: checkboxes
    id: provider
    attributes:
      label: Which provider would this enchantment improve?
      description: We currently offer three providers: authjs, local and refresh. If the enchanment is a general one, please select all three.
      options:
        - label: AuthJS
        - label: Local
        - label: Refresh
        - label: New Provider
  - type: checkboxes
    id: additional-info
    attributes:
      label: Additional information
      description: Additional information that helps us decide how to proceed.
      options:
        - label: Would you be willing to help implement this feature?
