name: 🐞 Bug report
description: Create a bug report for this project
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please help us finding and resolving problems.
  - type: textarea
    id: bug-env
    attributes:
      label: Environment
      description: You can use `npx nuxi info` to fill this section
      placeholder: Environment
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Provide a link to a repo that can reproduce the problem you ran into if you can.
      placeholder: Reproduction
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additonal
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if provided reproduction. Please try not to insert an image but copy paste the log text.
      render: shell
